name: EAS continous deployment


on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ—ï¸ Checkout code
        uses: actions/checkout@v4

      - name: ğŸš§ Setup Node
        uses: actions/setup-node@v3
      
      - name: ğŸª› Setup cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: ğŸ›’ Install dependencies
        run: npm ci
        shell: bash

      - name: ğŸš§ Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}

      - name: ğŸšš Build and deploy ğŸ“¦
        run: eas update --auto
        shell: bash
